# Generated by Django 6.0.2 on 2026-03-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonces',
            name='description',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anonces',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anonces',
            name='type',
            field=models.CharField(choices=[], default='Records', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anonces',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
