# Generated by Django 6.0.2 on 2026-03-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_anonces_description_anonces_sold_anonces_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anonces',
            new_name='Listing',
        ),
    ]
