# Generated by Django 6.0.2 on 2026-03-05 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename_anonces_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('Records', 'Disques'), ('Clothing', 'Vetements'), ('Posters', 'Affiches'), ('Miscellaneous', 'Divers')], max_length=100),
        ),
    ]
